# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{raccept}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sam Schenkman-Moore"]
  s.date = %q{2010-01-19}
  s.description = %q{This middleware turns Ruby objects that are not acceptable Rack bodies into xml or json depending upon the accepts header.}
  s.email = %q{samsm@samsm.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config.ru",
     "lib/raccept.rb",
     "test/helper.rb",
     "test/test_raccept.rb",
     "vendor/xml_serialization/MIT-LICENSE",
     "vendor/xml_serialization/README.markdown",
     "vendor/xml_serialization/Rakefile",
     "vendor/xml_serialization/VERSION.yml",
     "vendor/xml_serialization/lib/xml_serialization.rb",
     "vendor/xml_serialization/test/xml_serialization_test.rb",
     "vendor/xml_serialization/xml_serialization.gemspec"
  ]
  s.homepage = %q{http://github.com/samsm/raccept}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Transforms Ruby objects into xml or json based on accepts headers.}
  s.test_files = [
    "test/helper.rb",
     "test/test_raccept.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

